---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jumpshot-ext-authz
  name: jumpshot-ext-authz
  labels:
    app: jumpshot-ext-authz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jumpshot-ext-authz
  template:
    metadata:
      labels:
        app: jumpshot-ext-authz
    spec:
      containers:
      - name: jumpshot-ext-authz
        image: jumpshot-ext-authz
        args:
        - serve
        - --nats=nats://nats.nats.svc.cluster.local.:4222
        env:
        - name: ENV
          value: "development"
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 9091
          name: metrics
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
