---
apiVersion: v1
kind: Service
metadata:
  namespace: jumpshot-ext-authz
  name: jumpshot-ext-authz
spec:
  clusterIP: None
  selector:
    app: jumpshot-ext-authz
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090